name: Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu]
        python-version: ["3.10"]
        include:
          - os: Ubuntu
            image: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: SG60/setup-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Install black, isort, flake8
        run: pip install black isort flake8

      - name: Black
        run: poetry run python -m black . --check
        if: ${{ always() }}
      - name: ISort
        run: poetry run isort . --check --diff
        if: ${{ always() }}
      - name: Flake8
        run: poetry run flake8 .
        if: ${{ always() }}
